// Mocks generated by Mockito 5.3.0 from annotations
// in u_note_apps/test/core/view/bloc/u_note_event_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:u_note_apps/features/u_note_apps/data/models/models.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUNoteAuthenticationModel_0 extends _i1.SmartFake
    implements _i2.UNoteAuthenticationModel {
  _FakeUNoteAuthenticationModel_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [UNoteAuthenticationModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUNoteAuthenticationModel extends _i1.Mock
    implements _i2.UNoteAuthenticationModel {
  MockUNoteAuthenticationModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  _i2.UNoteAuthenticationModel copyWith(
          {String? email, String? id, String? name, String? photo}) =>
      (super.noSuchMethod(
          Invocation.method(#copyWith, [],
              {#email: email, #id: id, #name: name, #photo: photo}),
          returnValue: _FakeUNoteAuthenticationModel_0(
              this,
              Invocation.method(#copyWith, [], {
                #email: email,
                #id: id,
                #name: name,
                #photo: photo
              }))) as _i2.UNoteAuthenticationModel);
}
