// Mocks generated by Mockito 5.3.0 from annotations
// in u_note_apps/test/core/view/bloc/u_note_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:u_note_apps/core/errors/errors.dart' as _i9;
import 'package:u_note_apps/core/network/network.dart' as _i2;
import 'package:u_note_apps/features/u_note_apps/data/datasources/remote/remote.dart'
    as _i3;
import 'package:u_note_apps/features/u_note_apps/data/models/models.dart'
    as _i6;
import 'package:u_note_apps/features/u_note_apps/data/repository/authentication/u_note_authentication_repository_impl.dart'
    as _i7;
import 'package:u_note_apps/features/u_note_apps/domain/entities/authentication/u_note_authentication_entities.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeINetworkInfo_0 extends _i1.SmartFake implements _i2.INetworkInfo {
  _FakeINetworkInfo_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUNoteDataSourceRemoteFirebaseAuth_1 extends _i1.SmartFake
    implements _i3.UNoteDataSourceRemoteFirebaseAuth {
  _FakeUNoteDataSourceRemoteFirebaseAuth_1(
      Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUNoteAuthenticationEntities_2 extends _i1.SmartFake
    implements _i4.UNoteAuthenticationEntities {
  _FakeUNoteAuthenticationEntities_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUNoteAuthenticationModel_4 extends _i1.SmartFake
    implements _i6.UNoteAuthenticationModel {
  _FakeUNoteAuthenticationModel_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [UNoteAuthenticationRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUNoteAuthenticationRepositoryImpl extends _i1.Mock
    implements _i7.UNoteAuthenticationRepositoryImpl {
  MockUNoteAuthenticationRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.INetworkInfo get network => (super.noSuchMethod(
          Invocation.getter(#network),
          returnValue: _FakeINetworkInfo_0(this, Invocation.getter(#network)))
      as _i2.INetworkInfo);
  @override
  _i3.UNoteDataSourceRemoteFirebaseAuth get remoteFirebaseAuth =>
      (super.noSuchMethod(Invocation.getter(#remoteFirebaseAuth),
              returnValue: _FakeUNoteDataSourceRemoteFirebaseAuth_1(
                  this, Invocation.getter(#remoteFirebaseAuth)))
          as _i3.UNoteDataSourceRemoteFirebaseAuth);
  @override
  _i4.UNoteAuthenticationEntities get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
              returnValue: _FakeUNoteAuthenticationEntities_2(
                  this, Invocation.getter(#currentUser)))
          as _i4.UNoteAuthenticationEntities);
  @override
  _i8.Stream<_i4.UNoteAuthenticationEntities> get user =>
      (super.noSuchMethod(Invocation.getter(#user),
              returnValue: _i8.Stream<_i4.UNoteAuthenticationEntities>.empty())
          as _i8.Stream<_i4.UNoteAuthenticationEntities>);
  @override
  _i8.Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>
      authWithGoogleAccount() => (super.noSuchMethod(
          Invocation.method(#authWithGoogleAccount, []),
          returnValue:
              _i8.Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>.value(
                  _FakeEither_3<_i9.Failures, _i4.UNoteAuthenticationEntities>(
                      this,
                      Invocation.method(#authWithGoogleAccount, [])))) as _i8
          .Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>);
  @override
  _i8.Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>
      logOut() => (super.noSuchMethod(Invocation.method(#logOut, []),
          returnValue:
              _i8.Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>.value(
                  _FakeEither_3<_i9.Failures, _i4.UNoteAuthenticationEntities>(
                      this, Invocation.method(#logOut, [])))) as _i8
          .Future<_i5.Either<_i9.Failures, _i4.UNoteAuthenticationEntities>>);
}

/// A class which mocks [UNoteAuthenticationModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUNoteAuthenticationModel extends _i1.Mock
    implements _i6.UNoteAuthenticationModel {
  MockUNoteAuthenticationModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  _i6.UNoteAuthenticationModel copyWith(
          {String? email, String? id, String? name, String? photo}) =>
      (super.noSuchMethod(
          Invocation.method(#copyWith, [],
              {#email: email, #id: id, #name: name, #photo: photo}),
          returnValue: _FakeUNoteAuthenticationModel_4(
              this,
              Invocation.method(#copyWith, [], {
                #email: email,
                #id: id,
                #name: name,
                #photo: photo
              }))) as _i6.UNoteAuthenticationModel);
}
