// Mocks generated by Mockito 5.3.0 from annotations
// in u_note_apps/test/features/u_note_apps/data/repository/authentication/u_note_authentication_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:u_note_apps/core/network/network_info_impl.dart' as _i5;
import 'package:u_note_apps/features/u_note_apps/data/datasources/datasources.dart'
    as _i3;
import 'package:u_note_apps/features/u_note_apps/data/models/models.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUNoteAuthenticationModel_0 extends _i1.SmartFake
    implements _i2.UNoteAuthenticationModel {
  _FakeUNoteAuthenticationModel_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [UNoteDataSourceRemoteFirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockUNoteDataSourceRemoteFirebaseAuth extends _i1.Mock
    implements _i3.UNoteDataSourceRemoteFirebaseAuth {
  MockUNoteDataSourceRemoteFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.UNoteAuthenticationModel> get user =>
      (super.noSuchMethod(Invocation.getter(#user),
              returnValue: _i4.Stream<_i2.UNoteAuthenticationModel>.empty())
          as _i4.Stream<_i2.UNoteAuthenticationModel>);
  @override
  _i2.UNoteAuthenticationModel get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
              returnValue: _FakeUNoteAuthenticationModel_0(
                  this, Invocation.getter(#currentUser)))
          as _i2.UNoteAuthenticationModel);
  @override
  _i4.Future<_i2.UNoteAuthenticationModel> authWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#authWithGoogle, []),
              returnValue: _i4.Future<_i2.UNoteAuthenticationModel>.value(
                  _FakeUNoteAuthenticationModel_0(
                      this, Invocation.method(#authWithGoogle, []))))
          as _i4.Future<_i2.UNoteAuthenticationModel>);
  @override
  _i4.Future<_i2.UNoteAuthenticationModel> logOut() =>
      (super.noSuchMethod(Invocation.method(#logOut, []),
              returnValue: _i4.Future<_i2.UNoteAuthenticationModel>.value(
                  _FakeUNoteAuthenticationModel_0(
                      this, Invocation.method(#logOut, []))))
          as _i4.Future<_i2.UNoteAuthenticationModel>);
}

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i5.INetworkInfo {
  MockINetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: _i4.Future<bool>.value(false)) as _i4.Future<bool>);
}
